# 复习

# System.arraycopy();

```java
System.arraycopy(src,srcPos,desc,descPos,length);

src: 数据源

srcPos: 数据源开始的下标

dest:目标数组（目的地）

descPos: 目标数组开始的下标

length: 复制的长度 长度 数量 
       //数据源
        int[] arr = {10, 20, 30};
        //目的地
        int[] newArr = new int[3];

        System.arraycopy(arr,1,newArr,0,2);
        System.out.println(Arrays.toString(newArr));

```

# 异常

学习异常的目的：即使程序出现了bug 也要执行下去

## 异常体系：

![1604969520108](C:\Users\Administrator\AppData\Roaming\Typora\typora-user-images\1604969520108.png)

```java
Throwable:所有异常的祖师爷
    -- Error: 系统内部异常 不需要程序员处理
    
    -- Exception:需要程序员处理的异常
        -- 运行时异常： 程序跑起来 才会发生的异常  java
        -- 检查异常：  在代码编译时就会发生的异常   javac
     ArrayIndexOutofBoundsException 数组下标越界异常
        
     NullPointException  空指针异常
        
     InputMismatchException  输入不匹配异常
        
     IllegalArgumentException  参数异常
        .....
                
```

## 处理异常

### 1.自己处理异常 try{}catch(){}finally{}

```java
语法结构：
try{

可能发生异常的代码

}catch(异常类型 标识符){


}finally{


}

1.没有发生异常 不会执行 catch 
  发生了不能捕获的异常 
2.finally
  无论发生或者不发生异常 都会执行finally中的代码块
  使用   System.exit(0); 强制退出jvm
  
  
3.return 
  1.如果finally中有return 则 无论前面那个位置有return  最终返回的是 finlly中的return
  
  2.如果finally中没有return  其他位置有return 会先执行完 finally中的代码 再进行返回
  
4.catch(异常类型 标识符) 表示 已经创建完 异常类型的对象 

5.作用域问题  在 try{} 中声明的变量 无法 在 catch 和  finally中使用  

  如果一定要使用 需要把 变量 声明到 try{}外部
```



### 2.甩锅 抛出异常

#### throw:抛出

```java
throw throws区别？

1.位置不同
  throw在方法捏
  throws 方法的声明处
  
2.抛出的内容不同

  throw 后面是一个异常对象
  
  throws 后面有很多的异常类型
  
  
  注意： 如果throw 抛出的是一个运行时异常  那么 可以不用声明
                        抛出的是一个检查异常  那么 必须声明
                        
                      
                      
       在进行方法重写时 子类不能抛出比父类更大的异常
    
    
  
  



```

## 自定义异常

```java
1.新建一个类型

2.继承一个异常类

3.新建构造器 
   public 类名(String mess){
   
   	super(mess);
   }
```

